# Generated by Django 5.2 on 2025-05-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Игрок')),
                ('team', models.CharField(max_length=50, verbose_name='Команда')),
                ('role', models.CharField(max_length=50, verbose_name='Роль')),
                ('cl', models.IntegerField(verbose_name='ЛЧ')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('cost', models.CharField(max_length=50, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'игрок',
                'verbose_name_plural': 'игроки',
            },
        ),
    ]
