# Generated by Django 5.2 on 2025-05-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=70, unique=True, verbose_name='Игрок'),
        ),
    ]
