# Generated by Django 5.2 on 2025-05-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo_path',
            field=models.FilePathField(blank=True, null=True, verbose_name='Путь до фото'),
        ),
    ]
