# Generated by Django 5.2 on 2025-05-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_player_photo_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('pic', models.FilePathField(blank=True, null=True, verbose_name='Путь до фото')),
            ],
            options={
                'verbose_name': 'флаг',
                'verbose_name_plural': 'флаги',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=50, verbose_name='Команда')),
                ('pic', models.FilePathField(blank=True, null=True, verbose_name='Путь до фото')),
            ],
            options={
                'verbose_name': 'лого',
                'verbose_name_plural': 'лого',
            },
        ),
    ]
