# Generated by Django 5.2 on 2025-05-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_flag_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер в команде'),
        ),
    ]
